[video_banks]
; examples
bank1: ./videos/video1.mp4
    ./videos/video2.mp4
    ./videos/video3.mp4
bank2: ./videos/video4.mp4
    ./videos/video5.mp4
    ./videos/video6.mp4
[cameras]
; examples
numbers: 0
    2